# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: money_retrieval.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'money_retrieval.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15money_retrieval.proto\"\'\n\x15MoneyRetrievalRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x01\"C\n\x16MoneyRetrievalResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x18\n\x10retrieved_amount\x18\x02 \x01(\x01\x32T\n\x0eMoneyRetrieval\x12\x42\n\rRetrieveMoney\x12\x16.MoneyRetrievalRequest\x1a\x17.MoneyRetrievalResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'money_retrieval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MONEYRETRIEVALREQUEST']._serialized_start=25
  _globals['_MONEYRETRIEVALREQUEST']._serialized_end=64
  _globals['_MONEYRETRIEVALRESPONSE']._serialized_start=66
  _globals['_MONEYRETRIEVALRESPONSE']._serialized_end=133
  _globals['_MONEYRETRIEVAL']._serialized_start=135
  _globals['_MONEYRETRIEVAL']._serialized_end=219
# @@protoc_insertion_point(module_scope)
